In [73]:
import numpy as np
from Pyfhel import Pyfhel

HE = Pyfhel()           
HE.contextGen(scheme='bfv', n=2**14, t_bits=20)  
  
HE.keyGen()             


integer1 = np.array([-1], dtype=np.int64)
integer2 = np.array([0], dtype=np.int64)
ctxt1 = HE.encryptInt(integer1) 
ctxt2 = HE.encryptInt(integer2) 
print("3. Integer Encryption, ")
print("    int ",integer1,'-> ctxt1 ', type(ctxt1))
print("    int ",integer2,'-> ctxt2 ', type(ctxt2))

print(ctxt1)
print(ctxt2)

ctxtSum = ctxt1 + ctxt2         
ctxtSub = ctxt1 - ctxt2        
ctxtMul = ctxt1 * ctxt2        
print("4. Operating with encrypted integers")
print(f"Sum: {ctxtSum}")
print(f"Sub: {ctxtSub}")
print(f"Mult:{ctxtMul}")

resSum = HE.decryptInt(ctxt1) 
resSub = HE.decryptInt(ctxtSub)
resMul = HE.decryptInt(ctxtMul)
print("#. Decrypting result:")
print("     addition:       decrypt(ctxt1 + ctxt2) =  ", resSum)
print("     substraction:   decrypt(ctxt1 - ctxt2) =  ", resSub)
print("     multiplication: decrypt(ctxt1 + ctxt2) =  ", resMul)

3. Integer Encryption, 
    int  [-1] -> ctxt1  <class 'Pyfhel.PyCtxt.PyCtxt'>
    int  [0] -> ctxt2  <class 'Pyfhel.PyCtxt.PyCtxt'>
<Pyfhel Ciphertext at 0x7d920d5ac810, scheme=bfv, size=2/2, noiseBudget=361>
<Pyfhel Ciphertext at 0x7d920d5e2020, scheme=bfv, size=2/2, noiseBudget=361>
4. Operating with encrypted integers
Sum: <Pyfhel Ciphertext at 0x7d916ad6e340, scheme=bfv, size=2/2, noiseBudget=360>
Sub: <Pyfhel Ciphertext at 0x7d920d5e2e30, scheme=bfv, size=2/2, noiseBudget=360>
Mult:<Pyfhel Ciphertext at 0x7d920d5acc70, scheme=bfv, size=3/3, noiseBudget=329>
#. Decrypting result:
     addition:       decrypt(ctxt1 + ctxt2) =   [-1  0  0 ...  0  0  0]
     substraction:   decrypt(ctxt1 - ctxt2) =   [-1  0  0 ...  0  0  0]
     multiplication: decrypt(ctxt1 + ctxt2) =   [0 0 0 ... 0 0 0]


In [74]:
import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

model = SimpleModel(10, 5, 2)

# Iterate over model parameters and store them in a list
parameters = [param.detach().numpy().flatten().tolist() for param in model.parameters()]

In [76]:
import numpy as np

In [75]:
for name,param in model.named_parameters():
    print(name,param)

fc1.weight Parameter containing:
tensor([[ 0.3060, -0.0144,  0.1318,  0.2218,  0.1433,  0.1439,  0.1467, -0.2727,
         -0.2846,  0.0384],
        [-0.2232,  0.2830,  0.1916, -0.0389, -0.0466, -0.2913, -0.2327, -0.0047,
         -0.0414, -0.1866],
        [ 0.1535,  0.1491,  0.1326,  0.1122,  0.1713,  0.2192,  0.1130, -0.1315,
         -0.0750,  0.1408],
        [ 0.1116, -0.0235, -0.1091, -0.2589,  0.1263, -0.0775, -0.0336,  0.0224,
          0.1472,  0.2284],
        [ 0.2218, -0.2101,  0.2831, -0.0549, -0.2237,  0.0333, -0.1105,  0.1640,
         -0.0261,  0.0207]], requires_grad=True)
fc1.bias Parameter containing:
tensor([ 0.0256,  0.2550,  0.2365, -0.2353,  0.1270], requires_grad=True)
fc2.weight Parameter containing:
tensor([[-0.1177,  0.0714,  0.0324, -0.4062, -0.3705],
        [ 0.3670,  0.2836, -0.2308, -0.4158,  0.4045]], requires_grad=True)
fc2.bias Parameter containing:
tensor([0.2909, 0.1879], requires_grad=True)


In [77]:
for param in parameters:
    print(np.shape(param))
    print('-------')

(50,)
-------
(5,)
-------
(10,)
-------
(2,)
-------


In [86]:
encrypted_parameters = []
for param in parameters:
    encrypted_param = [HE.encrypt(np.array(int_param, dtype=np.double)) for int_param in param]
    encrypted_parameters.append(encrypted_param)
encrypted_parameters

[[<Pyfhel Ciphertext at 0x7d920d49aca0, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d49ba60, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d497a60, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d916933ee80, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d5e0e50, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d5eac00, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d499080, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d49b970, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d49b1f0, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d49b470, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d49ac50, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d49aac0, scheme=bfv, size=2/2, noiseBudget=361>,
  <Pyfhel Ciphertext at 0x7d920d499b70, 

In [87]:
len(encrypted_parameters[1])

5

In [88]:
decrypted_parameters = []
for param in encrypted_parameters:
    smaller = []
    for int_param in param:
        decrypted_param = HE.decrypt(int_param)
        smaller.append(decrypted_param)
    decrypted_parameters.append(smaller)
decrypted_parameters

[[array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0, 0, ..., 0, 0, 0]),
  array([0, 0,

In [89]:
for param in decrypted_parameters:
    print(np.shape(param))

(50, 16384)
(5, 16384)
(10, 16384)
(2, 16384)


In [91]:
np.unique(param[0])

array([0])

In [96]:
# !git clone https://github.com/OpenMined/TenSEAL.git
!pip install ./TenSEAL/. --break-system-packages

Defaulting to user installation because normal site-packages is not writeable
Processing ./TenSEAL
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for tenseal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3916 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/tenseal
      copying tenseal/__init__.py -> build/lib.linux-x86_64-cpython-311/tenseal
      copying tenseal/version.py -> build/lib.linux-x86_64-cpython-311/tenseal
      copying tenseal/enc_context.py -> build/lib.linux-x86_64-cpython-311/tenseal
      creating build/lib.linux-x86_64-cpython-311/tenseal/sealapi
      copying tenseal/sealapi/__init__.py -> build/lib.l

In [92]:
import tenseal as ts

# Setup TenSEAL context
context = ts.context(
            ts.SCHEME_TYPE.CKKS,
            poly_modulus_degree=8192,
            coeff_mod_bit_sizes=[60, 40, 40, 60]
          )
context.generate_galois_keys()
context.global_scale = 2**40

v1 = [0, 1, 2, 3, 4]
v2 = [4, 3, 2, 1, 0]

# encrypted vectors
enc_v1 = ts.ckks_vector(context, v1)
enc_v2 = ts.ckks_vector(context, v2)

result = enc_v1 + enc_v2
result.decrypt() # ~ [4, 4, 4, 4, 4]

result = enc_v1.dot(enc_v2)
result.decrypt() # ~ [10]

matrix = [
  [73, 0.5, 8],
  [81, -5, 66],
  [-100, -78, -2],
  [0, 9, 17],
  [69, 11 , 10],
]
result = enc_v1.matmul(matrix)
result.decrypt() # ~ [157, -90, 153]

kj/filesystem-disk-unix.c++:1703: warning: PWD environment variable doesn't match current directory; pwd = /home/salehahmad/Documents/NUCES/Sem 8/Information Security/Project/Federated-Learning-Basics


AttributeError: module 'pydantic.main' has no attribute 'ModelMetaclass'